config/routes.rb
Rails.application.routes.draw do

  root 'signin#signin', as: :signin, constraints: lambda { |req| req.session[:user_id].nil? }
  root 'admin#home', as: :admin_home, constraints: lambda { |req| ! req.session[:user_id].nil? }

  post '/' => 'signin#submit_signin'
  get '/signout' => 'signin#signout'

  scope 'flows' do
    get '' => 'flow#list'
    scope 'new' do
      get '' => 'flow#create', as: :create_flow
      post '' => 'flow#create'
    end
    scope ':flow_id' do
      get '' => 'flow#show', as: :show_flow
      post 'cancel' => 'flow#cancel', as: :cancel_flow
      post 'pause' => 'flow#pause', as: :pause_flow
      post 'resume' => 'flow#resume', as: :resume_flow
    end
  end

  scope 'handlers' do
    get '' => 'handler#list'
    scope ':name' do
      get '' => 'handler#show', as: :show_handler
    end
  end

  scope 'workers' do
    get '' => 'worker#list'
    scope ':worker_id' do
      get '' => 'worker#show', as: :show_worker
    end
  end
end

app/models/user.rb
class User < RedisModel
  attr_accessor :id, :email, :password_digest

  require 'bcrypt'
  include BCrypt
  before_create :assign_id
  before_create :hash_password
  validate :email_is_not_taken
  validate :email_is_valid
  validates :password, presence: true, on: :create


  def to_hash
    raw = {
      email: self.email,
      password_digest: password_digest
    }
  end

  def password
    @password ||= Password.new(password_digest)
  end

  def password=(new_password)
    @password = new_password
    self.password_digest = Password.create(@password)
  end

  def authenticate(given_password)
    password == given_password
  end

  protected

  def serialize
    return self.to_hash.to_json
  end

  def create
    run_callbacks :create do
      self.store
      true
    end
  end

  def store
    redis.multi do
      # Insert into redis:
      redis.set("distribot.#{table}.by.id:#{self.id}", self.serialize)
      # Save our email address-to-token:
      redis.set("distribot.#{table}.by.email:#{self.email}", self.id)
    end
  end

  private

  def hash_password
#    self.password_digest = @password
  end

  def assign_id
    self.id ||= SecureRandom.uuid
  end

  def email_is_valid
    if self.email.to_s.blank?
      self.errors.add :email, "can't be blank"
    end
    unless self.email.to_s =~ %r{^.+?@.+?\..+$}
      self.errors.add :email, 'invalid'
    end
  end

  def email_is_not_taken
    # Make sure that no user exists with the email address:
    other_user = User.find_by(email: self.email)
    if other_user && other_user.id != self.id
      self.errors.add :email, 'already taken'
    end
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate!
  before_filter :set_active_nav

  def home
    @email = current_user.email
  end

  private

  def set_active_nav
    @active_nav = :summary
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  config.whitelisted_ips = '0.0.0.0'

  def sign_in(user)
    if user
      session[:user_id] = user.id
    end
  end

  protected
  include ApplicationHelper

  def authenticate!
    unless signed_in?
      flash[:error] = "You must first sign in before requesting that page"
      return redirect_to :signin
    end
  end
end

app/controllers/flow_controller.rb
class FlowController < ApplicationController
  before_filter :set_active_nav

  def list
    @meta_title = 'Active Flows'
    @flows = Distribot::Flow.active
    render @flows.empty? ? :empty_list : :list
  end

  def create
    @meta_title = 'Create Flow'
    if request.method == 'POST'
      begin
        @flow = Distribot::Flow.create!(JSON.parse(params[:json], symbolize_names: true))
        flash[:notice] = 'Successfully Created'
        redirect_to show_flow_path(flow_id: @flow.id)
      rescue
        flash[:error] = 'There was a problem - please try again'
        begin
          @flow = Distribot::Flow.new(JSON.parse(params[:json]))
        rescue JSON::ParserError => e
          flash[:error] = "Invalid JSON: #{e}"
          @flow_json = params[:json]
          @flow = Distribot::Flow.new()
        end
      end
    else
      @flow = Distribot::Flow.new(
        phases: [
          {
            name: "start",
            is_initial: true,
            transitions_to: "finish"
          },
          {
            name: "finish",
            is_final: true,
          }
        ]
      )
    end
  end

  def show
    @flow = Distribot::Flow.find(params[:flow_id])
    @meta_title = "View Flow #{@flow.id}"
  end

  def pause
  end

  def resume
  end

  def cancel
  end

  private

  def set_active_nav
    @active_nav = :flows
  end
end

app/controllers/handler_controller.rb
class HandlerController < ApplicationController
  before_filter :set_active_nav

  def list
    @handlers = [ ]
  end

  def show
  end

  private

  def set_active_nav
    @active_nav = :handlers
  end
end

app/controllers/signin_controller.rb
class SigninController < ApplicationController
  def signin
  end

  def submit_signin
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      sign_in user
      redirect_to :admin_home
    else
      flash[:error] = 'Login failed. Please try again.'
      redirect_to :signin
    end
  end

  def signout
    session.delete :user_id
    redirect_to :signin
  end

end

app/controllers/worker_controller.rb
class WorkerController < ApplicationController
  before_filter :set_active_nav

  def list
    @workers = [ ]
  end

  def show
  end

  private

  def set_active_nav
    @active_nav = :workers
  end
end

app/controllers/workflow_controller.rb
class WorkflowController < ApplicationController
  before_filter :set_active_nav

  def list
    @meta_title = 'Active Flows'
    @workflows = Distribot::Workflow.active
    render @workflows.empty? ? :empty_list : :list
  end

  def create
    @meta_title = 'Create Flow'
    if request.method == 'POST'
      begin
        @workflow = Distribot::Workflow.create!(JSON.parse(params[:json], symbolize_names: true))
        flash[:notice] = 'Successfully Created'
        redirect_to show_workflow_path(workflow_id: @workflow.id)
      rescue
        flash[:error] = 'There was a problem - please try again'
        begin
          @workflow = Distribot::Workflow.new(JSON.parse(params[:json]))
        rescue JSON::ParserError => e
          flash[:error] = "Invalid JSON: #{e}"
          @workflow_json = params[:json]
          @workflow = Distribot::Workflow.new()
        end
      end
    else
      @workflow = Distribot::Workflow.new(
        phases: [
          {
            name: "start",
            is_initial: true,
            transitions_to: "finish"
          },
          {
            name: "finish",
            is_final: true,
          }
        ]
      )
    end
  end

  def show
    @workflow = Distribot::Workflow.find(params[:workflow_id])
    @meta_title = "View Flow #{@workflow.id}"
  end

  def pause
  end

  def resume
  end

  def cancel
  end

  private

  def set_active_nav
    @active_nav = :workflows
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def signed_in?
    session[:user_id] ? true : false
  end

  def current_user
    return nil unless session[:user_id]
    User.find(session[:user_id]) rescue nil
  end

  def active_nav(name)
    @active_nav ||= :home
    @active_nav == name ? 'active red inverted' : ''
  end
end

app/views/admin/home.html.erb
<div class="ui page grid">
  <div class="column">
    <div class="ui icon info message">
      <i class="info icon"></i>
      <div class="content">
        <div class="header">Distribot</div>
        <p>Data flows smoothly.</p>
      </div>
    </div>


  </div>
</div>

app/views/flow/create.html.erb
<div class="ui page grid">
  <div class="column">

    <div class="ui top attached header">
      <h2>Create a Flow</h2>
    </div>
    <%= form_tag(method: :post, class: 'ui form') do %>
      <div class="ui attached segment">
        <div class="ui required field">
          <textarea style="width: 100%; height: 400px; font-family: Courier New, mono;" name="json" required><%= @flow_json || @flow.send(:serialize) %></textarea>
        </div>
      </div>
      <div class="ui bottom attached segment right aligned">
        <button type="submit" class="ui button green right labeled icon">
          Create Flow
          <i class="save icon"></i>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/flow/empty_list.html.erb
<div class="ui page grid">
  <div class="column">
    <div class="ui icon info message">
      <i class="info icon"></i>
      <div class="content">
        <div class="header">There are no flows yet</div>
        <p>
          If you had flows, this is where they'd be.
        </p>
        <p>
          <a href="<%= create_flow_path %>" class="ui green right labeled icon button">
            Create New Flow
            <i class="right arrow icon"></i>
          </a>
        </p>
      </div>
    </div>

  </div>
</div>

app/views/flow/list.html.erb
<div class="ui page grid">
  <div class="column">
    <div class="ui two column grid">
      <div class="column">
        <h2>Flows</h2>
      </div>
      <div class="column right aligned">
        <a href="<%= create_flow_path %>" class="ui green button right labeled icon">
          Create New Flow
          <i class="right arrow icon"></i>
        </a>
      </div>
    </div>
    <div class="ui divider"></div>
    <table class="ui very basic celled collapsed table">
      <thead>
        <th class="six wide">Flows ID</th>
        <th class="four wide">Created</th>
        <th class="six wide">Progress</th>
      </thead>
      <tbody>
<%
  @flows.sort_by(&:created_at).reverse_each do |flow|
%>
        <tr>
          <td>
            <a href="<%= show_flow_path(flow_id: flow.id) %>"><%= flow.id %></a>
          </td>
          <td>
            <%= time_ago_in_words Time.at(flow.created_at) %> ago
          </td>
          <td>
<%
    flow.phases.each do |phase|
%>
            <div class="phase">
              <%= phase.name %>
              <% if flow.current_phase == phase.name %>
              <i class="left arrow icon"></i>
              <% end %>
            </div>
<%
    end
%>
          </td>
        </tr>
<%
  end
%>
      </tbody>
    </table>
  </div>
</div>

app/views/flow/show.html.erb
show.html.erb

app/views/handler/list.html.erb
<div class="ui page grid">
  <div class="column">
    <div class="ui two column grid">
      <div class="column">
        <h2>Handlers</h2>
      </div>
      <div class="column right aligned">
      </div>
    </div>
    <div class="ui divider"></div>
    <table class="ui very basic celled collapsed table">
      <thead>
        <th class="eight wide">Name</th>
        <th class="eight wide">Version</th>
      </thead>
      <tbody>
<%
  @handlers.sort_by(&:name).each do |handler|
%>
        <tr>
          <td>
            <a href="<%= show_handler_path(name: handler.name, version: handler.version) %>"><%= handler.name %></a>
          </td>
          <td>
            <%= handler.version %>
          </td>
        </tr>
<%
  end
%>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<head>
  <!-- Meta -->
  <meta charset="utf-8">
  <title><%= @meta_title || params[:action].titlecase %> | Distribot</title>
  <meta name="description" content="<%= content_for?(:meta_description) ? yield(:meta_description) : "" %>">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <meta name="author" content="">
  <link rel="canonical" href="">

  <!-- Favicon -->
  <link rel="shortcut icon" href="/favicon.ico">

  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= stylesheet_link_tag params[:controller], :media => 'all' if Rails.application.assets.find_asset("#{params[:controller]}.css") %>
  <%= javascript_include_tag "application" %>

  <%= javascript_include_tag params[:controller] if Rails.application.assets.find_asset("#{params[:controller]}.js") %>
  <%= javascript_include_tag "#{params[:controller]}/#{params[:action]}"  if Rails.application.assets.find_asset("#{params[:controller]}/#{params[:action]}.js") %>

  <%= yield(:head) %>
  <%= yield(:css) %>

</head>

<body class="<%= controller_name %>" id="<%= action_name %>">

<div class="ui secondary pointing menu fixed main-nav">
  <a class="brand item" href="/">
    <%= image_tag 'distribot-70x70.png', class: 'ui image' %>
    &nbsp;&nbsp;
    Distribot
  </a>
<% if signed_in? %>
  <a class="item <%= active_nav(:summary) %>" href="/">Summary</a>
  <a class="item <%= active_nav(:flows) %>" href="/flows">Flows</a>
  <a class="item <%= active_nav(:handlers) %>" href="/handlers">Handlers</a>
  <a class="item <%= active_nav(:workers) %>" href="/workers">Workers</a>
<% end %>
<% if signed_in? %>
<div id="account-menu" style="position: absolute; right: 8px; top: 12px; border-radius: 0px; white-space: nowrap">
  <div class="ui image label red"><%= current_user.email %>
    <a class="ui detail" href="/signout">Sign Out</a>
  </div>
</div>
<% end %>
</div>


<div id="main" class="ui grid">
  <div class="column">


  <% if flash[:error] || flash[:notice] %>
  <div class="ui page grid">
    <div class="row">
      <div class="column">
        <%= semantic_flash %>
      </div>
    </div>
  </div>
  <% end %>
  <%= yield %>
  </div>
</div>

</body>
</html>

app/views/signin/signin.html.erb
<div class="ui page stackable grid">
  <div class="row">
    <div class="four wide computer three wide tablet only column">
    </div>
    <div class="eight wide computer ten wide tablet sixteen wide mobile column">
    <%= form_tag({}, method: :post, class: "ui form signin-form") do %>
      <div class="ui segment top attached">
        <h3>Sign In</h3>
      </div>
      <div class="ui attached segment">
        <div class="ui required field">
          <label>Email:</label>
          <input type="email" name="email" class="ui input">
        </div>
        <div class="ui required field">
          <label>Password:</label>
          <input type="password" name="password" class="ui input">
        </div>
        <div class="ui error message"></div>
      </div>
      <div class="ui bottom attached segment right aligned">
        <button class="ui green right labeled icon button">
          Sign In
          <i class="ui right arrow icon"></i>
        </button>
      </div>
    <% end %>
    <div class="four wide computer three wide tablet only column">
    </div>
  </div>
</div>

app/views/worker/list.html.erb
<div class="ui page grid">
  <div class="column">
    <div class="ui two column grid">
      <div class="column">
        <h2>Workers</h2>
      </div>
      <div class="column right aligned">
      </div>
    </div>
    <div class="ui divider"></div>
    <table class="ui very basic celled collapsed table">
      <thead>
        <th class="six wide">Name</th>
      </thead>
      <tbody>
<%
  @workers.sort_by(&:name).each do |worker|
%>
        <tr>
          <td>
            <a href="<%= show_worker_path(name: worker.name) %>"><%= worker.name %></a>
          </td>
        </tr>
<%
  end
%>
      </tbody>
    </table>
  </div>
</div>

app/views/workflow/create.html.erb
<div class="ui page grid">
  <div class="column">

    <div class="ui top attached header">
      <h2>Create a Workflow</h2>
    </div>
    <%= form_tag(method: :post, class: 'ui form') do %>
      <div class="ui attached segment">
        <div class="ui required field">
          <textarea style="width: 100%; height: 400px; font-family: Courier New, mono;" name="json" required><%= @workflow_json || @workflow.send(:serialize) %></textarea>
        </div>
      </div>
      <div class="ui bottom attached segment right aligned">
        <button type="submit" class="ui button green right labeled icon">
          Create Workflow
          <i class="save icon"></i>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/workflow/empty_list.html.erb
<div class="ui page grid">
  <div class="column">
    <div class="ui icon info message">
      <i class="info icon"></i>
      <div class="content">
        <div class="header">There are no workflows yet</div>
        <p>
          If you had workflows, this is where they'd be.
        </p>
        <p>
          <a href="<%= create_workflow_path %>" class="ui green right labeled icon button">
            Create New Workflow
            <i class="right arrow icon"></i>
          </a>
        </p>
      </div>
    </div>

  </div>
</div>

app/views/workflow/list.html.erb
<div class="ui page grid">
  <div class="column">
    <div class="ui two column grid">
      <div class="column">
        <h2>Flows</h2>
      </div>
      <div class="column right aligned">
        <a href="<%= create_workflow_path %>" class="ui green button right labeled icon">
          Create New Flow
          <i class="right arrow icon"></i>
        </a>
      </div>
    </div>
    <div class="ui divider"></div>
    <table class="ui very basic celled collapsed table">
      <thead>
        <th class="six wide">Flows ID</th>
        <th class="four wide">Created</th>
        <th class="six wide">Progress</th>
      </thead>
      <tbody>
<%
  @workflows.sort_by(&:created_at).reverse_each do |workflow|
%>
        <tr>
          <td>
            <a href="<%= show_workflow_path(workflow_id: workflow.id) %>"><%= workflow.id %></a>
          </td>
          <td>
            <%= time_ago_in_words Time.at(workflow.created_at) %> ago
          </td>
          <td>
<%
    workflow.phases.each do |phase|
%>
            <div class="phase">
              <%= phase.name %>
              <% if workflow.current_phase == phase.name %>
              <i class="left arrow icon"></i>
              <% end %>
            </div>
<%
    end
%>
          </td>
        </tr>
<%
  end
%>
      </tbody>
    </table>
  </div>
</div>